use_frameworks!

target 'TKDataAnalysis_Example' do
  pod 'TKDataAnalysis', :path => '../'

  target 'TKDataAnalysis_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  pod 'FBSnapshotTestCase'
  end
end
